DROP TABLE certify;
DROP TABLE MALLS;
DROP TABLE PAYMENT_WAYS;
DROP TABLE BANKS;
DROP TABLE USERS;
DROP SEQUENCE SEQ_RECORD_NO;
DROP SEQUENCE SEQ_PAYMENT_NO;

CREATE TABLE MALLS(
    MALL_CODE   VARCHAR2(255),
    MALL_NAME   VARCHAR2(255),
    CONSTRAINT MALLS_PK PRIMARY KEY(MALL_CODE)
);

COMMENT ON TABLE MALLS IS '업체';
COMMENT ON COLUMN MALLS.MALL_CODE IS '업체 코드';
COMMENT ON COLUMN MALLS.MALL_NAME IS '업체명';


CREATE TABLE BANKS(
    BANK_NAME   VARCHAR2(255),
    URL         varchar2(255),
    CONSTRAINT BANKS_PK PRIMARY KEY(BANK_NAME)
);

COMMENT ON TABLE BANKS IS '은행';
COMMENT ON COLUMN BANKS.BANK_NAME IS '은행명';
COMMENT ON COLUMN BANKS.URL IS '주소';


CREATE TABLE USERS(
    USERID          VARCHAR2(255),
    PASSWORD        VARCHAR2(255),
    EMAIL           VARCHAR2(255),
    PHONE_NUMBER    VARCHAR2(255),
    NAME            VARCHAR2(255),
    CONSTRAINT USERS_PK PRIMARY KEY(USERID)
);

COMMENT ON TABLE USERS IS 'PG 사용자';
COMMENT ON COLUMN USERS.USERID IS '사용자 아이디';
COMMENT ON COLUMN USERS.PASSWORD IS '비밀번호';
COMMENT ON COLUMN USERS.EMAIL IS '사용자 이메일';
COMMENT ON COLUMN USERS.PHONE_NUMBER IS '사용자 전화번호';
COMMENT ON COLUMN USERS.NAME IS '사용자 이름';



CREATE TABLE PAYMENT_WAYS(
    PAYMENT_NO  NUMBER(38,0),
    USERID      VARCHAR2(255),
    BANK_NAME       VARCHAR2(255),
    MEANS           VARCHAR2(20) NOT NULL,
    CARD_OR_ACCOUNT_NUMBER  VARCHAR2(255) NOT NULL,
    CVC             VARCHAR2(255),
    END_YEAR        number(4),
    END_MONTH       number(2),
    CONSTRAINT PAYMENT_WAYS_PK PRIMARY KEY(PAYMENT_NO),
    CONSTRAINT PAYMENT_WAYS_FK_USERID FOREIGN KEY(USERID) REFERENCES USERS(USERID),
    CONSTRAINT PAYMENT_WAYS_FK_BANK_CODE FOREIGN KEY(BANK_NAME) REFERENCES BANKS(BANK_NAME) ON DELETE SET NULL,
    CONSTRAINT PAYMENT_WAYS_UNIQUE UNIQUE(CARD_OR_ACCOUNT_NUMBER)
);

COMMENT ON TABLE PAYMENT_WAYS IS '결제 수단 정보';
COMMENT ON COLUMN PAYMENT_WAYS.PAYMENT_NO IS '결제 수단 번호';
COMMENT ON COLUMN PAYMENT_WAYS.USERID IS '사용자 아이디';
COMMENT ON COLUMN PAYMENT_WAYS.BANK_NAME IS '은행명';
COMMENT ON COLUMN PAYMENT_WAYS.MEANS IS '결제 수단';
COMMENT ON COLUMN PAYMENT_WAYS.CARD_OR_ACCOUNT_NUMBER IS '결제 수단 번호';
COMMENT ON COLUMN PAYMENT_WAYS.CVC IS '카드의 3자리 번호';
COMMENT ON COLUMN PAYMENT_WAYS.END_YEAR IS '카드 만료일(연)';
COMMENT ON COLUMN PAYMENT_WAYS.END_MONTH IS '카드 만료일(월)';

CREATE SEQUENCE SEQ_PAYMENT_NO START WITH 1 INCREMENT BY 1 CACHE 2 NOCYCLE ORDER;




CREATE TABLE certify(
    email  varchar2(255),
    code     varchar2(255) NOT NULL,
    end_time    timestamp DEFAULT sysdate,
    CONSTRAINT certify_pk PRIMARY key(email)
);